import {
  Story,
  Post,
  TrendingTech,
  TechNewsItem,
  ResearchArticle,
  HackathonItem,
  UserProfile,
  PeerInterested,
  HackathonMaster,
  HackathonTeam,
} from './types';

export const HOBBIES_LIST = [
  'Reading',
  'Gaming',
  'Traveling',
  'Music',
  'Sports',
  'Photography',
  'Writing',
  'Content Creation',
  'Teaching',
  'Designing',
  'Drone/Tech',
  'Cooking',
  'Fitness',
  'Other',
];

export const DOMAINS_LIST = [
  'Web Development',
  'App Development',
  'AI / Machine Learning',
  'Data Science',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Blockchain',
  'AR/VR',
  'IoT',
  'Competitive Programming',
  'UI/UX Design',
  'Game Development',
  'Product Management',
  'Open Source',
  'Research',
];

export const POPULAR_COLLEGES = [
  'Indian Institute of Technology (IIT) Bombay',
  'Indian Institute of Technology (IIT) Delhi',
  'Indian Institute of Technology (IIT) Madras',
  'BITS Pilani',
  'National Institute of Technology (NIT) Trichy',
  'Delhi Technological University (DTU)',
  'Vellore Institute of Technology (VIT)',
  'International Institute of Information Technology (IIIT) Hyderabad',
  'Stanford University',
  'Carnegie Mellon University',
  'UC Berkeley',
  'Massachusetts Institute of Technology (MIT)',
];

export const INITIAL_USER: UserProfile = {
  id: 'usr_devansh',
  name: 'Devansh',
  email: 'devansh.sharma@college.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  college: 'Delhi Technological University (DTU)',
  hobbies: ['Gaming', 'Photography', 'Designing'],
  domains: ['Web Development', 'AI / Machine Learning', 'Cybersecurity'],
  skills: ['Java', 'Data Structures & Algorithms', 'Spring Boot', 'MySQL', 'Git', 'HTML'],
  certificates: [
    {
      id: 'cert_1',
      title: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services (AWS)',
      issueDate: '2026-05',
      expiryDate: '2029-05',
      url: 'https://aws.amazon.com/certification/',
      credentialId: 'AWS-7842910-CLD',
      category: 'Cloud Computing',
      isVerified: true,
    },
    {
      id: 'cert_2',
      title: 'Meta Front-End Developer Specialization',
      issuer: 'Coursera & Meta',
      issueDate: '2026-02',
      url: 'https://coursera.org/verify/meta-fed',
      credentialId: 'META-FED-99318',
      category: 'Web Development',
      isVerified: true,
    },
    {
      id: 'cert_3',
      title: 'Generative AI with Large Language Models',
      issuer: 'DeepLearning.AI & AWS',
      issueDate: '2026-01',
      url: 'https://deeplearning.ai',
      credentialId: 'DLAI-GENAI-4412',
      category: 'AI / Machine Learning',
      isVerified: true,
    },
  ],
  achievements: [
    {
      id: 'ach_1',
      title: '1st Place Winner - Smart India Hackathon (SIH) 2026',
      issuerOrOrg: 'Ministry of Education & AICTE',
      date: '2026-08',
      category: 'hackathon',
      rankOrPosition: '1st Place (National Winner)',
      badge: '🏆 1st Prize • ₹1,00,000',
      description: 'Led a 6-student engineering team developing an offline mesh emergency coordination system for disaster response zones. Selected #1 out of 1,800+ national finalist teams.',
      proofUrl: 'https://sih.gov.in',
      isVerified: true,
    },
    {
      id: 'ach_2',
      title: 'Global Rank 142 / 28,000 - LeetCode Biweekly Contest',
      issuerOrOrg: 'LeetCode',
      date: '2026-06',
      category: 'competition',
      rankOrPosition: 'Top 0.5% Worldwide (Knight Rating 2140+)',
      badge: '🥇 Top 0.5% Worldwide',
      description: 'Solved 4/4 algorithmic graph & dynamic programming problems in under 38 minutes. Maintained a 2100+ Knight competitive programming rating.',
      proofUrl: 'https://leetcode.com/devansh-codes',
      isVerified: true,
    },
    {
      id: 'ach_3',
      title: 'Global Finalist - Google Solution Challenge 2026',
      issuerOrOrg: 'Google Developer Student Clubs',
      date: '2026-04',
      category: 'competition',
      rankOrPosition: 'Top 10 Global Finalist',
      badge: '🏅 Top 10 Global Finalist',
      description: 'Engineered an accessible multimodal exam proctor and reader software for visually impaired university students using Gemini 2.5 and WebRTC.',
      proofUrl: 'https://developers.google.com/community/gdsc-solution-challenge',
      isVerified: true,
    },
    {
      id: 'ach_4',
      title: 'Open Source Maintainer - 500+ GitHub Stars',
      issuerOrOrg: 'GitHub Community',
      date: '2026-03',
      category: 'opensource',
      rankOrPosition: 'Core Creator & Maintainer',
      badge: '⭐ 500+ Stars',
      description: 'Created campus developer open-source utilities and real-time state synchronization libraries adopted by student developers across 14 universities.',
      proofUrl: 'https://github.com/devansh-codes',
      isVerified: true,
    },
  ],
  githubUsername: 'devansh-codes',
  isProfileComplete: true,
  termsAccepted: true,
  headline: 'Full-Stack Developer & AI Enthusiast | DTU CS 2026',
  bio: 'Building developer tools, participating in hackathons, and exploring high-performance distributed systems. Always open to collaborate on cool projects!',
  privateVault: {
    phone: '+91 98765 43210',
    personalEmail: 'devansh.career@gmail.com',
    careerTarget: 'Full-Stack Software Engineer & AI Systems Architect',
    resumeReplacementSlug: 'devansh-proof',
    accessLevel: 'recruiters_only',
    lastUpdated: 'Today',
    education: [
      {
        id: 'edu_1',
        institution: 'Delhi Technological University (DTU)',
        degree: 'Bachelor of Technology (B.Tech)',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: '2023',
        endYear: '2027',
        gradeOrCgpa: '8.95 / 10 CGPA',
        rollNumber: '2K23/CO/142',
        isCurrent: true,
        transcriptsUploaded: true,
      },
      {
        id: 'edu_2',
        institution: 'Delhi Public School, R.K. Puram',
        degree: 'Senior Secondary (CBSE Class XII)',
        fieldOfStudy: 'Science (Physics, Chemistry, Math, CS)',
        startYear: '2021',
        endYear: '2023',
        gradeOrCgpa: '96.4%',
        isCurrent: false,
        transcriptsUploaded: true,
      },
    ],
    projects: [
      {
        id: 'proj_1',
        title: 'Nexus Campus OS',
        description:
          'Distributed student microservices platform with real-time WebSocket campus alerts, peer matching algorithms, and automated team formation.',
        githubUrl: 'https://github.com/devansh-codes/nexus-campus-os',
        liveDemoUrl: 'https://nexus-campus-os.dev',
        techStack: ['React 19', 'TypeScript', 'Go', 'PostgreSQL', 'Docker', 'WebSockets'],
        stars: 142,
        forks: 28,
        featured: true,
        isProofVerified: true,
        architectureHighlights: 'Microservices architecture with 99.9% uptime and sub-50ms latency for peer sync.',
      },
      {
        id: 'proj_2',
        title: 'AI Proctor Gemini Engine',
        description:
          'Real-time multimodal proctoring system for competitive college exams & hackathons using Gemini API, WebRTC vision analysis, and audio anomaly detection.',
        githubUrl: 'https://github.com/devansh-codes/ai-proctor-gemini',
        liveDemoUrl: 'https://ai-proctor.college.dev',
        techStack: ['Python', 'FastAPI', 'Gemini 2.5', 'WebRTC', 'TailwindCSS'],
        stars: 320,
        forks: 64,
        featured: true,
        isProofVerified: true,
        architectureHighlights: 'Zero-latency streaming with Gemini Flash multimodal video frame ingestion.',
      },
      {
        id: 'proj_3',
        title: 'Smart India IoT Water Guard',
        description:
          'Hardware-software telemetry dashboard built for SIH with real-time turbidity, pH sensors, and automated contamination alerts for municipal pipelines.',
        githubUrl: 'https://github.com/devansh-codes/iot-water-guard',
        liveDemoUrl: 'https://waterguard-iot.org',
        techStack: ['C++', 'ESP32', 'MQTT', 'Node.js', 'Redis'],
        stars: 89,
        forks: 14,
        featured: false,
        isProofVerified: true,
        architectureHighlights: 'Low-power MQTT broker handling 10,000 sensor pulses per minute with solar battery failover.',
      },
    ],
  },
  stats: {
    posts: 18,
    connections: 482,
    hackathons: 6,
  },
};

export const INITIAL_STORIES: Story[] = [
  {
    id: 'story_current',
    userName: 'Your Story',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isCurrentUser: true,
    hasUnseen: false,
    storyImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=900&auto=format&fit=crop&q=80',
    caption: 'Late night coding at the campus incubation center! 💻☕',
    timestamp: '2h ago',
  },
  {
    id: 'story_riya',
    userName: 'Riya',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    hasUnseen: true,
    storyImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=900&auto=format&fit=crop&q=80',
    caption: 'Smart India Hackathon finals round starting today! 🏆 Wish us luck!',
    timestamp: '35m ago',
  },
  {
    id: 'story_aman',
    userName: 'Aman',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    hasUnseen: true,
    storyImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&auto=format&fit=crop&q=80',
    caption: 'GDSC Web3 Workshop live at Auditorium B 🚀',
    timestamp: '1h ago',
  },
  {
    id: 'story_kunal',
    userName: 'Kunal',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    hasUnseen: true,
    storyImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&auto=format&fit=crop&q=80',
    caption: 'Check out our new open-source devkit on GitHub!',
    timestamp: '3h ago',
  },
  {
    id: 'story_sneha',
    userName: 'Sneha',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    hasUnseen: true,
    storyImage: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=900&auto=format&fit=crop&q=80',
    caption: 'Campus sunrise before 8 AM Discrete Math lecture 🌅',
    timestamp: '4h ago',
  },
  {
    id: 'story_arjun',
    userName: 'Arjun',
    userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    hasUnseen: true,
    storyImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&auto=format&fit=crop&q=80',
    caption: 'Robotics lab testing autonomous obstacle avoidance rover 🤖',
    timestamp: '5h ago',
  },
  {
    id: 'story_muskan',
    userName: 'Muskan',
    userAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    hasUnseen: false,
    storyImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&auto=format&fit=crop&q=80',
    caption: 'Finally fixed that CSS layout bug after 4 hours 😅',
    timestamp: '6h ago',
  },
  {
    id: 'story_rohit',
    userName: 'Rohit',
    userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    hasUnseen: false,
    storyImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=900&auto=format&fit=crop&q=80',
    caption: 'Hackathon team brainstorming wireframes on Figma!',
    timestamp: '7h ago',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_featured',
    author: {
      name: 'CollegeCulture Official',
      username: 'collegeculture',
      avatar: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=150&auto=format&fit=crop&q=80',
      role: 'Campus Network',
      college: 'Global Student Hub',
      isVerified: true,
    },
    timestamp: '2h ago',
    bannerBadge: '#Hackathon',
    bannerTitle: 'Hackathon Prep Day',
    carouselCount: '1/5',
    images: [
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80',
    ],
    content: "Ideas, teams, and late night discussions — that's hackathon season! 🚀 Who's gearing up for this weekend's inter-college buildathon? Tag your team mates and let us know what stack you are building on!",
    tags: ['#Hackathon', '#CollegeLife', '#BuildTogether'],
    likes: 2419,
    isLiked: false,
    commentsCount: 96,
    shares: 231,
    isBookmarked: false,
    isFollowingAuthor: false,
    comments: [
      {
        id: 'c1',
        author: 'Arjun Mehta',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        college: 'IIT Delhi',
        text: 'Our team is shipping an AI powered lecture transcription & notes generator! React + FastAPI.',
        timestamp: '1h ago',
        likes: 14,
      },
      {
        id: 'c2',
        author: 'Sneha Rao',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        college: 'BITS Pilani',
        text: 'Looking forward to the mentoring sessions on Saturday! Will there be cloud credits provided?',
        timestamp: '45m ago',
        likes: 8,
      },
    ],
  },
  {
    id: 'post_riya',
    author: {
      name: 'Riya Sharma',
      username: 'riya_sharma',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'CS Undergrad',
      college: 'Delhi Technological University (DTU)',
      isVerified: true,
    },
    timestamp: '3h ago',
    content: 'Just submitted our project for the Smart India Hackathon!\nGrateful for this amazing team 💙',
    tags: ['#SIH2026', '#IoT', '#WomenInTech', '#Engineering'],
    images: [
      'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=1200&auto=format&fit=crop&q=80',
    ],
    likes: 412,
    isLiked: true,
    commentsCount: 38,
    shares: 45,
    isBookmarked: true,
    isFollowingAuthor: true,
    comments: [
      {
        id: 'c3',
        author: 'Devansh',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        college: 'DTU',
        text: 'So proud of you all! The dashboard UI and hardware sensor integration looked super slick!',
        timestamp: '2h ago',
        likes: 19,
      },
    ],
  },
  {
    id: 'post_poll',
    author: {
      name: 'Aman Verma',
      username: 'aman_v',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'Placement Coordinator',
      college: 'NIT Trichy',
      isVerified: false,
    },
    timestamp: '5h ago',
    content: "Placement Season Prep 📊 Seniors and batchmates, which primary programming language are you focusing on for technical interview coding rounds this semester?",
    tags: ['#Placements', '#DSA', '#CodingInterview', '#StudentLife'],
    poll: {
      question: 'Primary language for upcoming coding rounds:',
      totalVotes: 842,
      options: [
        { id: 'opt_cpp', text: 'C++ (STL & Speed)', votes: 412 },
        { id: 'opt_java', text: 'Java (OOPs & Enterprise)', votes: 268 },
        { id: 'opt_python', text: 'Python (Concise & Easy)', votes: 124 },
        { id: 'opt_go', text: 'Go / Others', votes: 38 },
      ],
      userVotedOptionId: 'opt_java',
    },
    likes: 310,
    isLiked: false,
    commentsCount: 52,
    shares: 18,
    isBookmarked: false,
    isFollowingAuthor: false,
  },
  {
    id: 'post_kunal',
    author: {
      name: 'Kunal Patel',
      username: 'kunal_dev',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'Full Stack & Open Source',
      college: 'VIT Vellore',
      isVerified: true,
    },
    timestamp: '8h ago',
    content: "🚀 Building an open-source peer tutoring platform for college students where seniors can conduct 1-on-1 mock interviews and code reviews for juniors.\n\nLooking for 1 UI/UX designer and 1 backend dev (Node.js/Go). Drop your GitHub handle or DM me if you'd like to collaborate!",
    tags: ['#OpenSource', '#WebDev', '#PeerTutoring', '#Collaborate'],
    likes: 189,
    isLiked: false,
    commentsCount: 27,
    shares: 31,
    isBookmarked: false,
  },
];

export const TRENDING_TECHS: TrendingTech[] = [
  {
    id: 1,
    name: 'Artificial Intelligence',
    category: 'Machine Learning & LLMs',
    mentions: '12.4K mentions',
    growth: '+28%',
    iconType: 'ai',
  },
  {
    id: 2,
    name: 'Web Development',
    category: 'Next.js, React & TypeScript',
    mentions: '10.2K mentions',
    growth: '+18%',
    iconType: 'code',
  },
  {
    id: 3,
    name: 'Cloud Computing',
    category: 'AWS, GCP & Kubernetes',
    mentions: '8.7K mentions',
    growth: '+22%',
    iconType: 'cloud',
  },
  {
    id: 4,
    name: 'Cybersecurity',
    category: 'Ethical Hacking & Zero Trust',
    mentions: '6.1K mentions',
    growth: '+15%',
    iconType: 'shield',
  },
  {
    id: 5,
    name: 'Data Science',
    category: 'Data Analytics & Pipelines',
    mentions: '5.9K mentions',
    growth: '+19%',
    iconType: 'chart',
  },
  {
    id: 6,
    name: 'Rust & Systems Programming',
    category: 'High Performance & Memory Safety',
    mentions: '4.8K mentions',
    growth: '+34%',
    iconType: 'code',
  },
  {
    id: 7,
    name: 'Agentic AI & MCP',
    category: 'Autonomous Multi-Agent Workflows',
    mentions: '4.3K mentions',
    growth: '+41%',
    iconType: 'ai',
  },
  {
    id: 8,
    name: 'DevOps & CI/CD',
    category: 'GitHub Actions, Terraform & Docker',
    mentions: '3.9K mentions',
    growth: '+14%',
    iconType: 'cloud',
  },
  {
    id: 9,
    name: 'Mobile App Development',
    category: 'Flutter, React Native & Swift',
    mentions: '3.6K mentions',
    growth: '+12%',
    iconType: 'code',
  },
  {
    id: 10,
    name: 'Blockchain & Web3',
    category: 'Smart Contracts, Solidity & Solana',
    mentions: '2.9K mentions',
    growth: '+11%',
    iconType: 'shield',
  },
];

export const TECH_NEWS: TechNewsItem[] = [
  {
    id: 'news_1',
    title: 'OpenAI Launches GPT-5 with Multimodal Capabilities',
    source: 'TechCrunch',
    timeAgo: '1h ago',
    logoType: 'openai',
    url: 'https://techcrunch.com',
  },
  {
    id: 'news_2',
    title: 'Google Announces New AI Tools for Students',
    source: 'The Verge',
    timeAgo: '4h ago',
    logoType: 'google',
    url: 'https://theverge.com',
  },
  {
    id: 'news_3',
    title: 'Microsoft Expands Copilot to More Developers',
    source: 'Microsoft Blog',
    timeAgo: '6h ago',
    logoType: 'microsoft',
    url: 'https://blogs.microsoft.com',
  },
];

export const RESEARCH_ARTICLES: ResearchArticle[] = [
  {
    id: 'res_1',
    title: 'A Survey on Large Language Models: Trends, Challenges and Future Directions',
    source: 'arXiv',
    timeAgo: '8h ago',
    iconType: 'arxiv',
    readTime: '12 min read',
  },
  {
    id: 'res_2',
    title: 'Advancements in Edge Computing for IoT Applications',
    source: 'IEEE',
    timeAgo: '12h ago',
    iconType: 'ieee',
    readTime: '15 min read',
  },
];

export const UPCOMING_HACKATHONS: HackathonItem[] = [
  {
    id: 'hack_google_ai',
    title: 'Google Build with AI Hackathon 2025',
    organizer: 'Google',
    organizerLogo: 'https://www.gstatic.com/images/branding/product/2x/google_cloud_64dp.png',
    prizePool: '$100,000+',
    mode: 'Online',
    location: 'Online (Global)',
    deadline: '25 Oct 2025',
    startDate: '1 Nov 2025',
    status: 'Ongoing',
    tags: ['AI/ML', 'Cloud Computing', 'Generative AI', 'Open Innovation', 'LLMs', 'Web'],
    banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    participants: 5200,
    participantsText: '5K+ participants',
    difficulty: 'Beginner Friendly',
    teamSize: 'Individual or Team (2-5 members)',
    eligibility: 'Open to Students & Developers',
    tagline: 'Create. Innovate. Impact with Gemini. Ideas today, A brighter tomorrow',
    about:
      'Join the Google Build with AI Hackathon 2025 and build innovative solutions using Gemini, Google Cloud, and other cutting-edge technologies. Open to students, developers, and creators worldwide. Access free Google Cloud credits, mentorship from Google Developer Experts, and showcase your project on the global stage.',
    isRegistered: true,
    userTeamId: 'team_codecrafters',
    timeline: [
      { event: 'Registration Opens', date: '1 Sep 2025', completed: true },
      { event: 'Registration Closes', date: '25 Oct 2025', completed: true },
      { event: 'Hackathon Starts', date: '1 Nov 2025', completed: false },
      { event: 'Results Announced', date: '10 Nov 2025', completed: false },
    ],
  },
  {
    id: 'hack_microsoft_cup',
    title: 'Microsoft Reimagine Cup 2025',
    organizer: 'Microsoft',
    prizePool: '$250,000+',
    mode: 'Hybrid',
    location: 'Global (Hybrid)',
    deadline: '12 Nov 2025',
    startDate: '18 Nov 2025',
    status: 'Registrations Open',
    tags: ['AI for Good', 'Sustainability', 'Web Development', 'Open Innovation'],
    banner: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80',
    participants: 10400,
    participantsText: '10K+ participants',
    difficulty: 'Student Teams',
    teamSize: 'Team (2-4 members)',
    eligibility: 'Enrolled College Students',
    tagline: 'Empower every student on the planet to achieve more through technology',
    about:
      'Solve real-world challenges with AI for a more sustainable, equitable future. Compete for global mentorship from Microsoft leaders, Azure sponsorship, and the coveted Imagine Cup trophy with $250,000 in grand prizes.',
    isRegistered: false,
    timeline: [
      { event: 'Registration Opens', date: '15 Sep 2025', completed: true },
      { event: 'Registration Closes', date: '12 Nov 2025', completed: false },
      { event: 'Hackathon Starts', date: '18 Nov 2025', completed: false },
      { event: 'World Finals', date: '15 Dec 2025', completed: false },
    ],
  },
  {
    id: 'hack_aws_builders',
    title: 'AWS Builders Hackathon',
    organizer: 'Amazon Web Services',
    prizePool: '$150,000+',
    mode: 'Online',
    location: 'Online',
    deadline: '30 Oct 2025',
    startDate: '5 Nov 2025',
    status: 'Registrations Open',
    tags: ['Cloud Computing', 'DevOps', 'Serverless', 'AI/ML'],
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
    participants: 8100,
    participantsText: '8K+ participants',
    difficulty: 'All Levels',
    teamSize: 'Individual or Team (1-5 members)',
    eligibility: 'Global builders & architects',
    tagline: 'Build, innovate and scale with resilient AWS services',
    about:
      'Build scalable serverless architectures, generative AI pipelines, and high availability systems using AWS Lambda, Bedrock, and SageMaker. Generous AWS cloud credits provided to all accepted teams.',
    isRegistered: false,
    timeline: [
      { event: 'Registration Opens', date: '1 Oct 2025', completed: true },
      { event: 'Registration Closes', date: '30 Oct 2025', completed: false },
      { event: 'Hackathon Starts', date: '5 Nov 2025', completed: false },
      { event: 'Demo Day', date: '20 Nov 2025', completed: false },
    ],
  },
  {
    id: 'hack_ieee_xtreme',
    title: 'IEEE Xtreme 18.0',
    organizer: 'IEEE',
    prizePool: 'Awards & Recognition',
    mode: 'Online',
    location: 'Global (Online)',
    deadline: '14 Nov 2025',
    startDate: '22 Nov 2025',
    status: 'Coming Soon',
    tags: ['Competitive Programming', 'Algorithms', 'Team Event', 'Global'],
    banner: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&auto=format&fit=crop&q=80',
    participants: 50000,
    participantsText: '50K+ participants',
    difficulty: 'Student Only',
    teamSize: 'Team (3 members)',
    eligibility: 'IEEE Student Members',
    tagline: 'Ideate • Build • Impact: A 24-hour global coding competition',
    about:
      'A 24-hour virtual programming competition where proctor-supervised collegiate teams solve a set of challenging algorithmic and data structure problems in real-time against top universities worldwide.',
    isRegistered: false,
    timeline: [
      { event: 'Proctor Approval', date: '20 Oct 2025', completed: false },
      { event: 'Registration Closes', date: '14 Nov 2025', completed: false },
      { event: 'Contest 24h Starts', date: '22 Nov 2025', completed: false },
      { event: 'Rankings Released', date: '28 Nov 2025', completed: false },
    ],
  },
  {
    id: 'hack_sih_2025',
    title: 'Smart India Hackathon 2025',
    organizer: 'Ministry of Education',
    prizePool: '₹1,00,00,000+',
    mode: 'Hybrid',
    location: 'Multiple Locations',
    deadline: '20 Oct 2025',
    startDate: '28 Oct 2025',
    status: 'Registrations Open',
    tags: ['Problem Solving', 'GovTech', 'Social Impact', 'Innovation'],
    banner: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&auto=format&fit=crop&q=80',
    participants: 120000,
    participantsText: '1L+ participants',
    difficulty: 'Student Teams',
    teamSize: 'Team (6 members, 1 female mandatory)',
    eligibility: 'Higher Education Institute Students',
    tagline: 'Solve real-world problems for a Viksit Bharat',
    about:
      'World’s biggest open innovation model. Address problem statements curated by Ministries, Departments, and Premier Industries to build scalable software and hardware solutions with direct government deployment pathways.',
    isRegistered: false,
    timeline: [
      { event: 'College Internal Hackathon', date: '15 Sep 2025', completed: true },
      { event: 'Idea Submission Closes', date: '20 Oct 2025', completed: false },
      { event: 'Grand Finale Nodal Centers', date: '28 Oct 2025', completed: false },
      { event: 'Winner Felicitation', date: '30 Oct 2025', completed: false },
    ],
  },
];

export const PEERS_INTERESTED: PeerInterested[] = [
  {
    id: 'peer_riya',
    name: 'Riya Sharma',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    college: 'IIIT Delhi',
    role: 'AI/ML Enthusiast | Open to team up!',
    lookingFor: 'Ideator, Developer',
    skills: ['Python', 'Machine Learning', 'NLP', 'Problem Solving'],
    connectionType: 'connection',
    github: 'riya-ml',
    isInvited: true,
  },
  {
    id: 'peer_aman',
    name: 'Aman Verma',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    college: 'IIT Kanpur',
    role: 'Full Stack Developer | Love building products',
    lookingFor: 'Designer, ML Expert',
    skills: ['React', 'Node.js', 'MongoDB', 'UI/UX'],
    connectionType: 'connection',
    github: 'aman-v',
    isInvited: true,
  },
  {
    id: 'peer_sneha',
    name: 'Sneha Patel',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    college: 'NIT Trichy',
    role: "Product Designer | Let's build something amazing!",
    lookingFor: 'Developers, PM',
    skills: ['Figma', 'UI/UX', 'Product Design', 'Branding'],
    connectionType: 'college',
    github: 'sneha-designs',
    isInvited: true,
  },
  {
    id: 'peer_arjun',
    name: 'Arjun Mehta',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    college: 'BITS Pilani',
    role: 'Cloud & DevOps | Always excited for hackathons',
    lookingFor: 'Developers, ML',
    skills: ['AWS', 'Docker', 'Kubernetes', 'System Design'],
    connectionType: 'peer',
    github: 'arjun-bot',
    isInvited: true,
  },
  {
    id: 'peer_kunal',
    name: 'Kunal Patel',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    college: 'VIT Vellore',
    role: 'Backend & Distributed Systems Specialist',
    lookingFor: 'Frontend Dev, Mobile Dev',
    skills: ['Go', 'PostgreSQL', 'Docker', 'gRPC'],
    connectionType: 'peer',
    github: 'kunal-dev',
    isInvited: false,
  },
  {
    id: 'peer_tanya',
    name: 'Tanya Sengupta',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    college: 'Delhi Technological University (DTU)',
    role: 'Frontend Wizard & Creative Developer',
    lookingFor: 'Backend Lead, AI Lead',
    skills: ['Three.js', 'Next.js', 'TailwindCSS', 'TypeScript'],
    connectionType: 'college',
    github: 'tanya-frontend',
    isInvited: false,
  },
];

export const HACKATHON_MASTERS: HackathonMaster[] = [
  {
    id: 'master_vikram',
    name: 'Dr. Vikram Aditya',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'Ex-Google AI Staff Researcher & Kaggle Grandmaster',
    organization: 'Google Developer Expert (AI)',
    rating: 4.9,
    reviewsCount: 38,
    mentoringFee: 499,
    currency: '₹',
    domains: ['Generative AI', 'PyTorch', 'Model Optimization', 'System Architecture'],
    skills: ['Gemini API', 'LangChain', 'Vector DBs', 'Scalability'],
    bio: 'Guided 14 teams to 1st place in international hackathons. I provide 1:1 architecture reviews, Gemini fine-tuning strategies, and judging pitch prep.',
    badges: ['Top Rated Master', 'Ex-Google', '14x Winner Mentor'],
    isHired: false,
  },
  {
    id: 'master_sarah',
    name: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Product Architect & YC Hackathon Winner',
    organization: 'Y Combinator Alumni',
    rating: 5.0,
    reviewsCount: 42,
    mentoringFee: 699,
    currency: '₹',
    domains: ['Product Design', 'Pitch Deck Storytelling', 'Full Stack'],
    skills: ['Pitching', 'UI/UX', 'Product Market Fit', 'Fast Prototyping'],
    bio: 'Former hackathon judge and YC founder. Specializing in high-impact 3-minute video demos, deck narration, and ruthless prototype scoping.',
    badges: ['YC Winner', 'Judge & Mentor', 'Pitch Specialist'],
    isHired: false,
  },
  {
    id: 'master_rohan',
    name: 'Rohan Singhania',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Cloud Infrastructure Lead & AWS Community Hero',
    organization: 'AWS / Cloud Architecture',
    rating: 4.8,
    reviewsCount: 29,
    mentoringFee: 399,
    currency: '₹',
    domains: ['Cloud Architecture', 'DevOps', 'Microservices'],
    skills: ['Kubernetes', 'Serverless', 'Terraform', 'CI/CD'],
    bio: 'Hands-on live debugging of deployment pipelines, real-time backend streaming, and production cloud infrastructure.',
    badges: ['AWS Hero', 'Cloud Mentor', 'DevOps Pro'],
    isHired: false,
  },
];

export const INITIAL_HACKATHON_TEAMS: HackathonTeam[] = [
  {
    id: 'team_codecrafters',
    name: 'CodeCrafters',
    motto: 'Turning ideas into intelligent solutions.',
    hackathonId: 'hack_google_ai',
    hackathonTitle: 'Google Build with AI 2025',
    hackathonBanner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    createdDate: '12 Oct 2025',
    visibility: 'Private',
    teamCode: 'CC2025AI',
    members: [
      {
        id: 'usr_devansh',
        name: 'You (Devansh)',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        college: 'DTU',
        role: 'Team Lead & Full Stack',
        isLead: true,
      },
      {
        id: 'peer_riya',
        name: 'Riya',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        college: 'IIIT Delhi',
        role: 'AI/ML Lead',
      },
      {
        id: 'peer_arjun',
        name: 'Arjun',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        college: 'BITS Pilani',
        role: 'Cloud & Backend',
      },
      {
        id: 'peer_sneha',
        name: 'Sneha',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        college: 'NIT Trichy',
        role: 'UI/UX & Video',
      },
      {
        id: 'peer_aman',
        name: 'Aman',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        college: 'IIT Kanpur',
        role: 'Frontend Dev',
      },
    ],
    tasks: [
      { id: 't1', title: 'Finalize idea & problem statement', completed: true },
      { id: 't2', title: 'Build prototype', completed: true },
      { id: 't3', title: 'Prepare presentation', completed: false },
      { id: 't4', title: 'Record demo video', completed: false },
      { id: 't5', title: 'Submit before deadline', completed: false },
    ],
    quickLinks: [
      { title: 'GitHub', url: 'https://github.com/codecrafters/ai-solution', icon: 'github' },
      { title: 'Google Drive', url: 'https://drive.google.com', icon: 'drive' },
      { title: 'Notion', url: 'https://notion.so', icon: 'notion' },
      { title: 'Figma', url: 'https://figma.com', icon: 'figma' },
    ],
    messages: [
      {
        id: 'msg_1',
        senderId: 'peer_riya',
        senderName: 'Riya Sharma',
        senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        senderRole: 'AI/ML Lead',
        isCurrentUser: false,
        text: 'Hey everyone! 🥳 Let’s finalize our idea for submission. Any updates on the model?',
        timestamp: '9:12 AM',
        reactions: [
          { emoji: '👍', count: 2 },
          { emoji: '❤️', count: 1 },
        ],
      },
      {
        id: 'msg_2',
        senderId: 'peer_arjun',
        senderName: 'Arjun Mehta',
        senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        senderRole: 'Cloud & Backend',
        isCurrentUser: false,
        text: 'Pushed the new model to GitHub. Check the repo and let me know your feedback.',
        timestamp: '9:18 AM',
        reactions: [
          { emoji: '🔥', count: 3 },
          { emoji: '👍', count: 1 },
        ],
        githubCard: {
          repo: 'github.com/codecrafters/ai-solution',
          description: 'AI solution for Google Build with AI 2025',
          url: 'https://github.com/codecrafters/ai-solution',
        },
      },
      {
        id: 'msg_3',
        senderId: 'usr_devansh',
        senderName: 'Devansh',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        senderRole: 'Team Lead',
        isCurrentUser: true,
        text: 'Looks great! I’ll work on the presentation slides today. We can connect at 6 PM for a quick sync.',
        timestamp: '9:25 AM',
      },
      {
        id: 'msg_4',
        senderId: 'peer_sneha',
        senderName: 'Sneha Patel',
        senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        senderRole: 'UI/UX & Video',
        isCurrentUser: false,
        text: 'Nice! I’ll handle the demo video and UI part. Also sharing a reference doc for the submission guidelines.',
        timestamp: '9:28 AM',
        reactions: [{ emoji: '👍', count: 2 }],
        attachment: {
          name: 'Build with AI - Guidelines.pdf',
          size: '2.4 MB • PDF',
          type: 'pdf',
        },
      },
      {
        id: 'msg_5',
        senderId: 'peer_aman',
        senderName: 'Aman Verma',
        senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        senderRole: 'Frontend Dev',
        isCurrentUser: false,
        text: 'Let’s quickly assign tasks. I’ll create a checklist.',
        timestamp: '9:32 AM',
      },
    ],
  },
  {
    id: 'team_hackverse',
    name: 'HackVerse',
    motto: 'Algorithms meet creative engineering.',
    hackathonId: 'hack_ieee_xtreme',
    hackathonTitle: 'IEEE Xtreme 18.0',
    hackathonBanner: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&auto=format&fit=crop&q=80',
    createdDate: 'Yesterday',
    visibility: 'Private',
    teamCode: 'HV18XT',
    members: [],
    tasks: [],
    quickLinks: [],
    messages: [
      {
        id: 'hv_1',
        senderId: 'peer_sneha',
        senderName: 'Sneha Rao',
        senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        isCurrentUser: false,
        text: 'Sneha: Let’s meet at 8 PM for dynamic programming practice.',
        timestamp: 'Yesterday',
      },
    ],
  },
  {
    id: 'team_innovatex',
    name: 'InnovateX',
    motto: 'GovTech solutions for Bharat.',
    hackathonId: 'hack_sih_2025',
    hackathonTitle: 'Smart India Hackathon',
    hackathonBanner: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&auto=format&fit=crop&q=80',
    createdDate: 'Yesterday',
    visibility: 'Private',
    teamCode: 'SIH2025IX',
    members: [],
    tasks: [],
    quickLinks: [],
    messages: [
      {
        id: 'ix_1',
        senderId: 'peer_riya',
        senderName: 'Riya',
        senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        isCurrentUser: false,
        text: 'Riya: Shared the document with hardware sensor schematics.',
        timestamp: 'Yesterday',
      },
    ],
  },
  {
    id: 'team_dswizards',
    name: 'DS Wizards',
    motto: 'Data Science & Predictive Intelligence.',
    hackathonId: 'hack_google_ai',
    hackathonTitle: 'Google Build with AI',
    createdDate: '20 Sep',
    visibility: 'Public',
    teamCode: 'DSWIZ',
    members: [],
    tasks: [],
    quickLinks: [],
    messages: [
      {
        id: 'ds_1',
        senderId: 'peer_aman',
        senderName: 'Aman',
        senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        isCurrentUser: false,
        text: 'Aman: 👍',
        timestamp: '20 Sep',
      },
    ],
  },
  {
    id: 'team_buildwithus',
    name: 'BuildWithUs',
    motto: 'Reimagining climate sustainability.',
    hackathonId: 'hack_microsoft_cup',
    hackathonTitle: 'Microsoft Reimagine Cup',
    createdDate: '19 Sep',
    visibility: 'Private',
    teamCode: 'BWU2025',
    members: [],
    tasks: [],
    quickLinks: [],
    messages: [
      {
        id: 'bwu_1',
        senderId: 'peer_kunal',
        senderName: 'Kunal',
        senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        isCurrentUser: false,
        text: 'Kunal: Anyone available for Azure credits setup?',
        timestamp: '19 Sep',
      },
    ],
  },
];

export const INTERNSHIPS_DATA: import('./types').InternshipItem[] = [
  {
    id: 'intern_infosys',
    title: 'Frontend Development Intern',
    company: 'Infosys',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    location: 'Indore, MP',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹25,000/month',
    duration: '3–6 months',
    eligibility: 'Graduate / Final Year',
    tags: ['Web Development', 'React', 'JavaScript', 'HTML/CSS', 'Git'],
    postedTime: 'Posted 2 days ago',
    deadline: 'Apply by 15 Oct 2025',
    isFeatured: true,
    isVerified: true,
    openings: 50,
    testType: 'Application Test + Interview',
    testDate: '15 Oct 2025',
    testCentre: 'Infosys Indore Campus',
    registrationFee: '₹299',
    about: 'Work on modern web applications, collaborate with experienced developers and contribute to real-world products used by global clients.',
    responsibilities: [
      'Develop and maintain frontend applications using React and TypeScript',
      'Work with design and product teams to translate Figma prototypes into performant UI',
      'Optimize web applications for maximum speed and cross-browser scalability',
      'Participate in code reviews, bug fixes, and agile team sprint discussions',
    ],
    skillsRequired: ['HTML', 'CSS', 'JavaScript', 'React', 'Git', 'Problem Solving'],
    selectionProcess: [
      {
        step: 1,
        title: 'Registration & Application',
        description: 'Pay registration fee and submit your verified student application.',
      },
      {
        step: 2,
        title: 'Online Aptitude Test',
        description: 'Comprehensive test covering quantitative, logical reasoning, and programming fundamentals.',
        details: 'Date: 15 Oct 2025 | Duration: 90 mins | Test Centre: Infosys Indore Campus | Fee: ₹299 (non-refundable)',
      },
      {
        step: 3,
        title: 'Technical Interview',
        description: 'Shortlisted candidates will be invited for live coding and technical problem solving.',
      },
      {
        step: 4,
        title: 'HR Interview',
        description: 'Final round with HR team covering culture fit, relocation, and offer rollout.',
      },
    ],
  },
  {
    id: 'intern_google',
    title: 'Software Engineering Intern',
    company: 'Google',
    companyLogo: 'https://www.gstatic.com/images/branding/product/2x/googleg_48dp.png',
    location: 'Bengaluru, KA (Hybrid)',
    mode: 'Hybrid',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹1,00,000/month',
    duration: '8–12 weeks',
    eligibility: 'Final Year / Graduate',
    tags: ['Software Development', 'Python', 'Distributed Systems', 'Go', 'Algorithms'],
    postedTime: 'Posted 2 days ago',
    deadline: 'Apply by 20 Oct 2025',
    isFeatured: true,
    isVerified: true,
    openings: 25,
    about: 'Join Google’s core engineering teams to solve complex algorithmic and distributed computing challenges touching billions of active users.',
    responsibilities: [
      'Design, build, test, and release reliable distributed systems at massive scale',
      'Collaborate with senior software engineers, research scientists, and product managers',
      'Write clean, idiomatic, test-driven production code',
    ],
    skillsRequired: ['Python', 'C++', 'Java', 'Distributed Systems', 'Algorithms'],
    selectionProcess: [
      { step: 1, title: 'Resume Screening', description: 'Review of GitHub, projects, and academic background.' },
      { step: 2, title: 'Google Online Assessment', description: '2 DSA coding problems on Google assessment platform.' },
      { step: 3, title: 'Technical Rounds (2x)', description: '45-minute live technical interviews with Google engineers.' },
      { step: 4, title: 'Team Matching & Offer', description: 'Match with engineering teams and offer letter issuance.' },
    ],
  },
  {
    id: 'intern_microsoft',
    title: 'Product Management Intern',
    company: 'Microsoft',
    companyLogo: 'https://images.unsplash.com/photo-1583321500900-82807e458f3c?w=150&auto=format&fit=crop&q=80',
    location: 'Hyderabad, TS (On-site)',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹80,000/month',
    duration: '12 weeks',
    eligibility: 'Pre-final / Final Year',
    tags: ['Product Management', 'Strategy', 'Analytics', 'UX Research', 'Agile'],
    postedTime: 'Posted 3 days ago',
    deadline: 'Apply by 18 Oct 2025',
    isVerified: true,
    openings: 15,
    about: 'Define product visions, user journeys, and feature roadmaps for Microsoft Cloud & AI platforms.',
    responsibilities: [
      'Conduct customer interviews and extract quantitative insights from telemetry data',
      'Draft detailed Product Requirement Documents (PRDs) and wireframes',
      'Work alongside engineering leads to prioritize roadmap deliverables',
    ],
    skillsRequired: ['Product Sense', 'Data Analysis', 'User Research', 'Wireframing', 'Communication'],
  },
  {
    id: 'intern_amazon',
    title: 'SDE Intern',
    company: 'Amazon',
    companyLogo: 'https://images.unsplash.com/photo-1523474255658-4af61b168344?w=150&auto=format&fit=crop&q=80',
    location: 'Remote',
    mode: 'Remote',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹90,000/month',
    duration: '10–12 weeks',
    eligibility: 'Final Year / Graduate',
    tags: ['Software Development', 'Java', 'System Design', 'AWS', 'Microservices'],
    postedTime: 'Posted 4 days ago',
    deadline: 'Apply by 25 Oct 2025',
    isVerified: true,
    openings: 40,
    about: 'Build resilient services powering AWS cloud and Amazon e-commerce infrastructure.',
    responsibilities: [
      'Write highly maintainable, secure Java and cloud microservices',
      'Optimize query throughput and latency in distributed DynamoDB and S3 architectures',
      'Participate in on-call shadowing and deployment automation',
    ],
    skillsRequired: ['Java', 'Object Oriented Design', 'Data Structures', 'AWS Basics'],
  },
  {
    id: 'intern_flipkart',
    title: 'Data Science Intern',
    company: 'Flipkart',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&auto=format&fit=crop&q=80',
    location: 'Bengaluru, KA (Hybrid)',
    mode: 'Hybrid',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹70,000/month',
    duration: '6 months',
    eligibility: 'Pre-final / Final Year',
    tags: ['Data Science', 'Machine Learning', 'SQL', 'Deep Learning', 'Statistics'],
    postedTime: 'Posted 1 day ago',
    deadline: 'Apply by 22 Oct 2025',
    isVerified: true,
    openings: 12,
    about: 'Leverage predictive machine learning models for customer demand forecasting, search ranking, and supply chain logistics.',
    responsibilities: [
      'Train, fine-tune, and evaluate deep learning and recommendation models',
      'Run large-scale statistical experiments and A/B test validations',
      'Deploy inference pipelines on GPU clusters',
    ],
    skillsRequired: ['Python', 'SQL', 'PyTorch/TensorFlow', 'Scikit-Learn', 'Statistics'],
  },
  {
    id: 'intern_zomato',
    title: 'Frontend Developer Intern',
    company: 'Zomato',
    companyLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=150&auto=format&fit=crop&q=80',
    location: 'Gurugram, HR (Hybrid)',
    mode: 'Hybrid',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹60,000/month',
    duration: '6 months',
    eligibility: 'Pre-final / Final Year',
    tags: ['Frontend Development', 'React', 'TypeScript', 'Tailwind CSS', 'Redux'],
    postedTime: 'Posted 5 days ago',
    deadline: 'Apply by 28 Oct 2025',
    isVerified: true,
    openings: 20,
    about: 'Craft smooth food ordering interfaces, live delivery tracking maps, and merchant analytics dashboards.',
    responsibilities: [
      'Build snappy, responsive web interfaces with 60fps animations',
      'Integrate WebSocket feeds for live GPS driver tracking and status updates',
      'Conduct accessibility audits and page load speed optimizations',
    ],
    skillsRequired: ['React', 'TypeScript', 'CSS/Tailwind', 'REST APIs', 'State Management'],
  },
  {
    id: 'intern_swiggy',
    title: 'Business Analyst Intern',
    company: 'Swiggy',
    companyLogo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=150&auto=format&fit=crop&q=80',
    location: 'Bengaluru, KA (On-site)',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹50,000/month',
    duration: '3–6 months',
    eligibility: 'Pre-final / Final Year',
    tags: ['Business Analysis', 'Excel', 'Data Analysis', 'Tableau', 'Strategy'],
    postedTime: 'Posted 6 days ago',
    deadline: 'Apply by 30 Oct 2025',
    isVerified: true,
    openings: 10,
    about: 'Analyze hyperlocal consumer demand trends, delivery fleet efficiency, and promo ROI.',
    responsibilities: [
      'Build interactive dashboards on PowerBI and Tableau for city operations teams',
      'Formulate business metrics hypotheses and evaluate experiment outcomes',
      'Present weekly performance summaries to category leadership',
    ],
    skillsRequired: ['Advanced Excel', 'SQL', 'Tableau', 'Problem Solving', 'Data Storytelling'],
  },
  {
    id: 'intern_zoho',
    title: 'Software Development Intern',
    company: 'Zoho',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=150&auto=format&fit=crop&q=80',
    location: 'Indore, MP (On-site)',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹30,000/month',
    duration: '3–6 months',
    eligibility: 'Final Year / Graduate',
    tags: ['Java', 'Backend', 'Problem Solving', 'Database Design'],
    postedTime: 'Posted 4 days ago',
    deadline: 'Apply by 20 Oct 2025',
    isVerified: true,
    testType: 'Online Test + Interview',
    testDate: '20 Oct 2025',
    testCentre: 'Zoho Indore Office',
    registrationFee: '₹199',
    openings: 30,
    about: 'Build enterprise-grade SaaS products with high concurrency, security, and developer ergonomics.',
    responsibilities: [
      'Develop backend service modules using clean Java architectures',
      'Optimize relational database queries for millions of records',
      'Write automated unit and integration tests',
    ],
    skillsRequired: ['Java', 'Data Structures', 'RDBMS', 'OOPS'],
  },
  {
    id: 'intern_mygov',
    title: 'Product & Policy Research Intern',
    company: 'MyGov Innovation Lab',
    companyLogo: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=150&auto=format&fit=crop&q=80',
    location: 'Indore, MP (Hybrid)',
    mode: 'Hybrid',
    type: 'Part-time',
    isPaid: true,
    stipend: '₹10,000/month',
    duration: '2–4 months',
    eligibility: 'Undergrad / Graduate',
    tags: ['Policy Research', 'Data Analysis', 'Communication', 'GovTech'],
    postedTime: 'Posted 5 days ago',
    deadline: 'Apply by 22 Oct 2025',
    isVerified: true,
    testType: 'Case Study Test + Interview',
    testDate: '22 Oct 2025',
    testCentre: 'DAVV, Indore',
    registrationFee: '₹150',
    openings: 8,
    about: 'Research digital public infrastructure usage and citizen feedback on government initiatives.',
    responsibilities: [
      'Analyze sentiment from citizen consultation portals',
      'Prepare policy briefs and infographic summaries for public release',
    ],
    skillsRequired: ['Policy Analysis', 'Research Methodology', 'Writing', 'Data Synthesis'],
  },
  {
    id: 'intern_localvibe',
    title: 'UI/UX Design Intern',
    company: 'LocalVibe (Indore-based Startup)',
    companyLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    location: 'Indore, MP (On-site)',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹12,000/month',
    duration: '3 months',
    eligibility: 'Any Year',
    tags: ['UI/UX', 'Figma', 'User Research', 'Design Systems'],
    postedTime: 'Posted 6 days ago',
    deadline: 'Apply by 25 Oct 2025',
    isVerified: true,
    testType: 'Design Challenge + Interview',
    testDate: '25 Oct 2025',
    testCentre: 'Innovate Indore Hub',
    openings: 5,
    about: 'Design local neighborhood discovery experiences for young college students.',
    responsibilities: [
      'Create high-fidelity mobile prototypes in Figma',
      'Build scalable component design systems and style guides',
    ],
    skillsRequired: ['Figma', 'Prototyping', 'Visual Design', 'Wireframing'],
  },
  {
    id: 'intern_agnikul',
    title: 'Aerospace Research Intern',
    company: 'Agnikul Cosmos',
    companyLogo: 'https://images.unsplash.com/photo-1517976487502-5f654b1f69fb?w=150&auto=format&fit=crop&q=80',
    location: 'Indore, MP (On-site)',
    mode: 'On-site',
    type: 'Full-time',
    isPaid: true,
    stipend: '₹20,000/month',
    duration: '3–6 months',
    eligibility: 'Pre-final / Final Year',
    tags: ['Research', 'Simulation', 'Python', 'CAD', 'Rocketry'],
    postedTime: 'Posted 1 week ago',
    deadline: 'Apply by 28 Oct 2025',
    isVerified: true,
    testType: 'Aptitude Test + Interview',
    testDate: '28 Oct 2025',
    testCentre: 'IIT Indore (Test Centre)',
    openings: 6,
    about: 'Work on launch vehicle simulations, rocket engine thermodynamics, and 3D printing research.',
    responsibilities: [
      'Execute CFD simulations and compile thermal telemetry analysis',
      'Assist propulsion engineers with ground testing documentation',
    ],
    skillsRequired: ['Python', 'Simulation', 'CAD', 'Thermodynamics'],
  },
];
